---

apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: chaos
spec:
  serviceAccount: pod-controller
  containers:
    - name: shell
      image: python:3.9-alpine
      command:
        - sleep
        - infinite