---

kind: Namespace
apiVersion: v1
metadata:
  name: chaos

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-controller
  namespace: chaos
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: chaos
  name: pod-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-controller
subjects:
  - kind: ServiceAccount
    name: pod-controller
    namespace: chaos
roleRef:
  kind: ClusterRole
  name: pod-controller
  apiGroup: rbac.authorization.k8s.io